name: Pipeline con Errores
on:
 push:
  branches: ramma1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Saludo
        run: echo "Hola clase"

      - name: Validar Secret
        run: echo "El token es ${{secrets.TOKEN}}"